language: r
r:
  - oldrel
  - release
  - devel

sudo: false
cache: packages

warnings_are_errors: true

r_packages:
  - dplyr

r_github_packages:
  - End-to-end-provenance/provParseR
  - End-to-end-provenance/rdt
  - End-to-end-provenance/rdtLite

notifications:
  slack: endtoendprovenance:DNYqXZWhV1c3eRhkjGYyjCEv


